name: Cargo Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: transport and gnupg
        run: sudo apt install -y curl apt-transport-https gnupg
      - name : keys
        run: curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1
      - name: add couchdb to repositories
        run: echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ jammy  main" | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null
      - name: update
        run: sudo apt update
      - name: Install dependencies
        run: sudo apt -f install -y couchdb
      - name: env file
        run: echo "USERNAME=admin\nPASSWORD\nURL=http://localhost:5984" > .env
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
