name: Cargo Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        couchdb: ["3.3"] #"3.2", "3.1", "2.3"

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Start CouchDB
        uses: iamssen/couchdb-github-action@master
        with:
          couchdb-version: ${{ matrix.couchdb }}
      - name: env file
        run: echo -e "URL=http://localhost:5984\nUSERNAME=admin\nPASSWORD=password" > .env
      - name: cat env
        run: cat .env
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
