name: Cargo Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: update
        run: sudo apt update && sudo apt install -y curl apt-transport-https gnupg
      - name: add couchdb key
        run: curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1
      - name: source repository
        run: source /etc/os-release
      - name: Install dependencies
        run: sudo apt install -y couchdb
      - name: env file
        run: echo "USERNAME=admin\nPASSWORD\nURL=http://localhost:5984" > .env
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
